* Blog/Website

This is my (Price Hiller) personal website/blog/whatever else it may become.

** Reporting Issues

If you have found an issue within my site, say incorrect spelling, incorrect grammar, etc. open an issue on
[[https://github.com/treatybreaker/Blog][github]] and please report it.

**** Reporting Issues that my code sucks/is bad/should be burnt inside a supernovae explosion

Yeah, you're probably right. But on a serious note, if you see anything that is extremely terrible code-wise do let me
know. I won't accept PRs for code modifications here as this repository is just a mirror, but if you want to open one to
share something new with me or show me how I could do something better I'm totally down and I may even copy your stuff
and cosign you when I merge it into the primary. Best way to learn is to be brought down a peg in my experience, so I'm
open to it.

** Miscellaneous

*** I just want to make a comment.

Go [[https://github.com/treatybreaker/Blog/discussions/new?category=general][here]]

*** I didn't understand something or want to ask a question about an article

Go [[https://github.com/treatybreaker/Blog/discussions/new?category=q-a][here]]

*** I am looking through this and you've set all of this stuff up, but you haven't written jack-

🤷
